url_full: https://stakiran.github.io/tit/
# For jekyll-seo-tag.
# This plugin's completion like this:
#
#   https://stakiran.github.io/tit/tit/2020/01/26_minimalist_apartment.html
#                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# So, i use not an url but domain without / suffix.
url: https://stakiran.github.io
lang: ja-JP
title: stakiran's tit
theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-seo-tag
